import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const distDir = path.join(__dirname, '../dist')

const cssPath = path.join(distDir, 'style.css')
const jsPath = path.join(distDir, 'cg-api-doc.js')
const htmlPath = path.join(distDir, 'index.html')

if (fs.existsSync(cssPath) && fs.existsSync(jsPath)) {
  const cssCode = fs.readFileSync(cssPath, 'utf8')
  const jsCode = fs.readFileSync(jsPath, 'utf8')

  // 1. Create the all-in-one .min.js bundle (injects CSS dynamically)
  const injectionCode = `(function(){
    if(typeof document !== 'undefined'){
      var style = document.createElement('style');
      style.textContent = ${JSON.stringify(cssCode)};
      document.head.appendChild(style);
    }
  })();\n`
  const minJsPath = path.join(distDir, 'cg-api-doc.min.js')
  fs.writeFileSync(minJsPath, injectionCode + jsCode, 'utf8')
  console.log('Successfully generated cg-api-doc.min.js (injected styles)!')

  // 2. Output the standalone CSS file
  const finalCssPath = path.join(distDir, 'cg-api-doc.css')
  fs.writeFileSync(finalCssPath, cssCode, 'utf8')
  console.log('Successfully generated cg-api-doc.css!')

  // 3. Delete the temporary style.css generated by Vite
  if (fs.existsSync(cssPath)) {
    fs.unlinkSync(cssPath)
    console.log('Removed temporary style.css.')
  }

  // 4. Clean up all other files in the dist directory except our target outputs
  const allowedFiles = ['cg-api-doc.js', 'cg-api-doc.css', 'cg-api-doc.min.js']
  if (fs.existsSync(distDir)) {
    const files = fs.readdirSync(distDir)
    for (const file of files) {
      const filePath = path.join(distDir, file)
      const stat = fs.statSync(filePath)
      if (stat.isFile() && !allowedFiles.includes(file)) {
        fs.unlinkSync(filePath)
        console.log(`Removed unneeded build file: dist/${file}`)
      }
    }
  }

  // 5. Clean up the root-level cg-api-doc.js file if it exists from previous builds
  const rootJsPath = path.join(__dirname, '../cg-api-doc.js')
  if (fs.existsSync(rootJsPath)) {
    fs.unlinkSync(rootJsPath)
    console.log('Removed legacy root-level cg-api-doc.js.')
  }
} else {
  console.error('Could not find dist/style.css or dist/cg-api-doc.js!')
}
